/**
 * Skill map (GENERATED by scripts/emit-graph.mjs). The stage→stage prerequisite backbone is
 * DERIVED from concepts.ts via deriveStageEdges() + transitiveReduction(); only the stage
 * nodes, the goal achievement, and the soft orientation links below are overlay.
 */
import type { SkillGraph, SkillNode, SkillEdge } from "../types";
import { deriveStageEdges, transitiveReduction } from "./derive";

const concept = (
  id: string, branch: SkillNode["branch"], lessonId: string, title: string,
  shortDescription: string, position: { x: number; y: number },
): SkillNode => ({ id, kind: "concept", branch, lessonId, title, shortDescription, position });

const achievement = (
  id: string, branch: SkillNode["branch"], title: string, shortDescription: string,
  assessmentIds: string[], position: { x: number; y: number },
): SkillNode => ({ id, kind: "achievement", branch, title, shortDescription, assessmentIds, position });

const NODES: SkillNode[] = [
  concept("c-s0", "setup-onboarding", "stage-0", "Setup & onboarding", "deployment path selection, authentication precedence, non-interactive authentication", { x: 60, y: 40 }),
  concept("c-s1", "config-memory", "stage-1", "Config & memory (CLAUDE.md, settings)", "CLAUDE.md memory files, guidance vs enforcement, settings precedence and merging", { x: 360, y: 40 }),
  concept("c-s2", "permissions-security-gov", "stage-2", "Permissions, security & governance", "settings scope precedence, deny/ask/allow rule evaluation, enforcement vs guidance", { x: 660, y: 40 }),
  concept("c-s3", "skills-hooks-commands", "stage-3", "Skills, hooks & commands", "configuration scope and precedence, shared vs. personal config placement, hooks on lifecycle events", { x: 60, y: 240 }),
  concept("c-s4", "subagents-agent-teams", "stage-4", "Subagents & agent teams", "Choosing a multi-context approach, Subagent, Definition scope and precedence", { x: 360, y: 240 }),
  concept("c-s5", "mcp", "stage-5", "MCP (connecting tools)", "MCP server, MCP scope (local / project / user), Configuration-as-code distribution", { x: 660, y: 240 }),
  concept("c-s6", "plugins-distribution", "stage-6", "Plugins & distribution", "plugin, marketplace, settings scope", { x: 60, y: 440 }),
  concept("c-s7", "automation-ci-integratio", "stage-7", "Automation, CI & integrations", "headless (print) mode, CI authentication, cost and loop bounding", { x: 360, y: 440 }),
  concept("c-s8", "optimal-use-context-cost", "stage-8", "Optimal use, context & cost", "Shared CLAUDE.md, Context as the fundamental constraint, Per-feature precedence and four config levels", { x: 660, y: 440 }),
  concept("c-s9", "surfaces-mobility", "stage-9", "Surfaces & mobility", "surfaces share one engine and config, auth method determines available features, config mobility across surfaces", { x: 60, y: 640 }),
  concept("c-s10", "monitoring-analytics-tro", "stage-10", "Monitoring, analytics & troubleshooting", "Adoption & ROI analytics dashboards, GitHub contribution attribution, OpenTelemetry cost & usage export", { x: 360, y: 640 }),
  concept("c-s11", "enterprise-providers-gat", "stage-11", "Enterprise providers & gateways", "Model pinning, Small/fast model cost trap, Provider enable & routing precedence", { x: 660, y: 640 }),
  achievement("a-goal", "enterprise-providers-gat", "Capstone: team Claude Code + Codex setup", "Demonstrate the goal of the course.", ["cap-goal"], { x: 360, y: 860 }),
];

const STAGE_TO_NODE: Record<string, string> = {};
for (const n of NODES) if (n.lessonId) STAGE_TO_NODE[n.lessonId] = n.id;

const DERIVED_PREREQS: [string, string][] = deriveStageEdges()
  .map(([a, b]) => [STAGE_TO_NODE[a], STAGE_TO_NODE[b]] as [string, string])
  .filter(([a, b]) => !!a && !!b);

const CONCEPT_PREREQS: [string, string][] = transitiveReduction(
  Array.from(new Map(DERIVED_PREREQS.map((e) => [`${e[0]}>${e[1]}`, e])).values()),
);

const ACHIEVEMENT_PREREQS: [string, string][] = [["c-s11", "a-goal"]];

const PREREQS: [string, string][] = [...CONCEPT_PREREQS, ...ACHIEVEMENT_PREREQS];

const ORIENTS: [string, string][] = [
  ["c-s0", "c-s1"],
];

const EDGES: SkillEdge[] = [
  ...PREREQS.map(([source, target], i) => ({ id: `e${i}`, source, target, kind: "prerequisite_for" as const })),
  ...ORIENTS.map(([source, target], i) => ({ id: `o${i}`, source, target, kind: "orients" as const })),
];

export const SKILL_GRAPH: SkillGraph = { nodes: NODES, edges: EDGES };

export const ROOT_GOAL_ID = "a-goal";

export function nodeById(id: string): SkillNode | undefined {
  return SKILL_GRAPH.nodes.find((n) => n.id === id);
}
export function nodeForLesson(lessonId: string): SkillNode | undefined {
  return SKILL_GRAPH.nodes.find((n) => n.lessonId === lessonId);
}
export function achievements(): SkillNode[] {
  return SKILL_GRAPH.nodes.filter((n) => n.kind === "achievement");
}
export function prereqsOf(id: string): string[] {
  return SKILL_GRAPH.edges.filter((e) => e.kind === "prerequisite_for" && e.target === id).map((e) => e.source);
}
export function ancestorsOf(id: string): Set<string> {
  const out = new Set<string>();
  const walk = (n: string) => { for (const p of prereqsOf(n)) if (!out.has(p)) { out.add(p); walk(p); } };
  walk(id);
  return out;
}
