/**
 * Deterministic emitter (kb→course engine): course-spec JSON → graph.ts (the skill-map
 * overlay). One stage node per stage (auto-laid-out), one achievement node for the goal;
 * the concept→concept backbone is DERIVED from concepts.ts via deriveStageEdges (not
 * hand-authored). Mirrors the structure of a hand-written graph.ts so the derived map,
 * glossary, and debates all work.
 *
 *   node scripts/emit-graph.mjs <course-spec.json> [out.ts]   (default out: /tmp/gen-graph.ts)
 */
import { readFileSync, writeFileSync } from "node:fs";

const specPath = process.argv[2];
const outPath = process.argv[3] || "/tmp/gen-graph.ts";
if (!specPath) { console.error("usage: emit-graph.mjs <spec.json> [out.ts]"); process.exit(2); }
const spec = JSON.parse(readFileSync(specPath, "utf8"));
const q = (s) => JSON.stringify(String(s ?? ""));

const stages = spec.stages; // [{id:"stage-N", branch, title}]
const nodeId = (s) => "c-" + s.id.replace("stage-", "s");
const ACH = "a-goal";
const ASSESS = "cap-goal";

// grid layout: 3 columns, vertical ladder
const NODES = stages.map((s, i) => {
  const x = 60 + (i % 3) * 300;
  const y = 40 + Math.floor(i / 3) * 200;
  const blurb = (spec.concepts.filter((c) => c.stage === s.id).map((c) => c.term).slice(0, 3).join(", ")) || s.title;
  return `  concept(${q(nodeId(s))}, ${q(s.branch)}, ${q(s.id)}, ${q(s.title)}, ${q(blurb)}, { x: ${x}, y: ${y} }),`;
}).join("\n");

const goalBranch = stages[stages.length - 1]?.branch || "decision";
const lastNode = nodeId(stages[stages.length - 1]);
const achY = 60 + Math.ceil(stages.length / 3) * 200;

const ts = `/**
 * Skill map (GENERATED by scripts/emit-graph.mjs). The stage→stage prerequisite backbone is
 * DERIVED from concepts.ts via deriveStageEdges() + transitiveReduction(); only the stage
 * nodes, the goal achievement, and the soft orientation links below are overlay.
 */
import type { SkillGraph, SkillNode, SkillEdge } from "../types";
import { deriveStageEdges, transitiveReduction } from "./derive";

const concept = (
  id: string, branch: SkillNode["branch"], lessonId: string, title: string,
  shortDescription: string, position: { x: number; y: number },
): SkillNode => ({ id, kind: "concept", branch, lessonId, title, shortDescription, position });

const achievement = (
  id: string, branch: SkillNode["branch"], title: string, shortDescription: string,
  assessmentIds: string[], position: { x: number; y: number },
): SkillNode => ({ id, kind: "achievement", branch, title, shortDescription, assessmentIds, position });

const NODES: SkillNode[] = [
${NODES}
  achievement(${q(ACH)}, ${q(goalBranch)}, ${q("Capstone: " + (spec.meta?.domain || "the goal"))}, ${q("Demonstrate the goal of the course.")}, [${q(ASSESS)}], { x: 360, y: ${achY} }),
];

const STAGE_TO_NODE: Record<string, string> = {};
for (const n of NODES) if (n.lessonId) STAGE_TO_NODE[n.lessonId] = n.id;

const DERIVED_PREREQS: [string, string][] = deriveStageEdges()
  .map(([a, b]) => [STAGE_TO_NODE[a], STAGE_TO_NODE[b]] as [string, string])
  .filter(([a, b]) => !!a && !!b);

const CONCEPT_PREREQS: [string, string][] = transitiveReduction(
  Array.from(new Map(DERIVED_PREREQS.map((e) => [\`\${e[0]}>\${e[1]}\`, e])).values()),
);

const ACHIEVEMENT_PREREQS: [string, string][] = [[${q(lastNode)}, ${q(ACH)}]];

const PREREQS: [string, string][] = [...CONCEPT_PREREQS, ...ACHIEVEMENT_PREREQS];

const ORIENTS: [string, string][] = [
  [${q(nodeId(stages[0]))}, ${q(nodeId(stages[1] || stages[0]))}],
];

const EDGES: SkillEdge[] = [
  ...PREREQS.map(([source, target], i) => ({ id: \`e\${i}\`, source, target, kind: "prerequisite_for" as const })),
  ...ORIENTS.map(([source, target], i) => ({ id: \`o\${i}\`, source, target, kind: "orients" as const })),
];

export const SKILL_GRAPH: SkillGraph = { nodes: NODES, edges: EDGES };

export const ROOT_GOAL_ID = ${q(ACH)};

export function nodeById(id: string): SkillNode | undefined {
  return SKILL_GRAPH.nodes.find((n) => n.id === id);
}
export function nodeForLesson(lessonId: string): SkillNode | undefined {
  return SKILL_GRAPH.nodes.find((n) => n.lessonId === lessonId);
}
export function achievements(): SkillNode[] {
  return SKILL_GRAPH.nodes.filter((n) => n.kind === "achievement");
}
export function prereqsOf(id: string): string[] {
  return SKILL_GRAPH.edges.filter((e) => e.kind === "prerequisite_for" && e.target === id).map((e) => e.source);
}
export function ancestorsOf(id: string): Set<string> {
  const out = new Set<string>();
  const walk = (n: string) => { for (const p of prereqsOf(n)) if (!out.has(p)) { out.add(p); walk(p); } };
  walk(id);
  return out;
}
`;
writeFileSync(outPath, ts);
console.log(`✓ emitted ${outPath} — ${stages.length} stage nodes + 1 achievement (backbone derived)`);
